# Generated by Django 4.2.16 on 2025-11-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_oscu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_copy',
            field=models.BooleanField(default=False, help_text='Is this a copy of the original receipt'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_receipt_no',
            field=models.CharField(blank=True, help_text='Original receipt number if this is a copy', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data for receipt', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_type',
            field=models.CharField(choices=[('normal', 'Normal Sale'), ('copy', 'Copy Receipt'), ('proforma', 'Proforma Invoice'), ('training', 'Training Mode')], default='normal', help_text='Receipt type per KRA specification', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund/Credit Note')], default='sale', help_text='Transaction type (sale or refund)', max_length=20),
        ),
    ]
