# Generated by Django 4.2.16 on 2025-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra_oscu', '0003_add_digitax_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Automatically renew subscription'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, help_text='Date of last successful payment', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text='Date when subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='Date when subscription started', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('active', 'Active Subscription'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', help_text='Subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Date when trial period ends', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('starter', 'Starter Plan'), ('business', 'Business Plan'), ('enterprise', 'Enterprise Plan')], default='free', help_text='Current subscription plan', max_length=50),
        ),
    ]
