# Generated by Django 4.2.16 on 2026-02-10 06:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kra_oscu', '0004_add_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Plan name', max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free Plan'), ('starter', 'Starter Plan'), ('business', 'Business Plan'), ('enterprise', 'Enterprise Plan'), ('custom', 'Custom Plan')], max_length=20)),
                ('description', models.TextField(help_text='Plan description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Plan price', max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('lifetime', 'Lifetime')], max_length=20)),
                ('invoice_limit_per_month', models.IntegerField(default=-1, help_text='Monthly invoice limit (-1 for unlimited)')),
                ('device_limit', models.IntegerField(default=1, help_text='Maximum number of devices')),
                ('user_limit', models.IntegerField(default=1, help_text='Maximum number of users')),
                ('features', models.JSONField(default=dict, help_text='Plan features as JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular plan')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('trial_days', models.IntegerField(default=30, help_text='Free trial days')),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'price'],
                'indexes': [models.Index(fields=['plan_type'], name='subscriptio_plan_ty_9c7ad6_idx'), models.Index(fields=['is_active'], name='subscriptio_is_acti_4d4352_idx'), models.Index(fields=['sort_order'], name='subscriptio_sort_or_87c1cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Free Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('invoices_used_this_month', models.IntegerField(default=0)),
                ('devices_used', models.IntegerField(default=0)),
                ('users_used', models.IntegerField(default=1)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal')], default='mpesa', max_length=50)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('company', models.OneToOneField(help_text='Company with this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='kra_oscu.company')),
                ('plan', models.ForeignKey(help_text='Current subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='kra_oscu.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment provider', max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('billing_period_start', models.DateTimeField()),
                ('billing_period_end', models.DateTimeField()),
                ('payment_metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment data')),
                ('subscription', models.ForeignKey(help_text='Subscription this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='kra_oscu.subscription')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company'], name='subscriptio_company_28682a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_572d44_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='subscriptio_current_0ac39a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_payment_date'], name='subscriptio_next_pa_c57233_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription'], name='payments_subscri_9bd444_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_transaction_id'], name='payments_externa_c63e06_idx'),
        ),
    ]
